# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: mv ./dist ./.circleci
      - persist_to_workspace:
          root: .
          paths:
            - .circleci
  push:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: create docker image
          command: |
            cd ~/.circleci
            docker build . -t inquiry-front
      - run: docker tag inquiry-front ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/inquiry-front:$CIRCLE_SHA1
      - run: docker push ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/inquiry-front:$CIRCLE_SHA1

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - push:
          requires:
            - build
